version: '3'

services:
  api:
    build: ./
    image: myimage
    command: uvicorn main:app --port 9000 --host 0.0.0.0 --reload
    ports:
      - 9000:9000
    networks:
      - test_network

networks:
  test_network:
    driver: bridge